# Generated by Django 5.2.7 on 2025-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_priority_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('age', models.PositiveSmallIntegerField()),
                ('tg_id', models.BigIntegerField()),
            ],
        ),
    ]

